version: "3"

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8000:8000
        volumes:
            - .:/var/www:cached

    db:
        image: bitnami/postgresql:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: emprega_api
